server:
  port: 8010
eureka:
  instance:
    status-page-url-path: ${management.contextPath}/info
    health-check-url: ${management.contextPath}/health
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false